### ISSUE TITLE
Do you any algorithm in Perl?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/perl#1]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Perl](https://github.com/AllAlgorithms/Perl) this case.

**Comment by sdeseille** [comment]
Hello

I will contribute to the Perl implementation of algorithms

regards

**Comment by abranhe** [comment]
@sdeseille That would be great!

**Comment by sdeseille** [comment]
thank i took a look on your website, it is a lot of work.

Well done !

regards

**Comment by polettix** [comment]
... I know it's from one year ago... but I added an implementation of A*, I hope this project is still alive! 😁
